### ISSUE TITLE
Structure still a mess after 10,000 epochs

### ISSUE THREAD

**Issue by gezmi** [kiharalab/Distance-AF#2]
Hi,

I want to model a di-UBL protein. I ran the MMseqs2 notebook in multimer mode, then renamed and renumbered the second chain (the script was complaining about having more than one chain). I ran Distance-Af, however, still at the end of the 10,000 epochs, the structue still looked like as attached.

What could have gone wrong? In the fasta file, I had the 2 sequence (without :, maybe that was the problem). How could it work with more than one chain?
![diufm1](https://github.com/kiharalab/Distance-AF/assets/13509667/2d1632af-7a40-4370-ba4b-646ed5407303)

**Comment by Zhang038** [comment]
Hello, thanks for  you interest in our work. For your questions:
1.  Your target is dimer, but the predicted structure is 1 chain.  `without :` is the issue I guess,`fasta1:fasta2` is the correct way to generate embedding for multimer.
2. Current Distance-AF works on monomer target only. I am afraid it cannot be directly to applied on your dimer target. Now we are still developing multimer version and hope it can come out soon.
If there are other questions, please don't hesitate to let me know.
