### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by 957-z** [kiharalab/Distance-AF#5]
AttributeError: module 'jax.random' has no attribute 'PRNGKeyArray' for the last prediction part in Distance_AF_embedding_FullMSA.ipynb

**Comment by Zhang038** [comment]
Hello, thanks to your interests in our work. I have fixed this problem now, it is raised as 'PRNGKeyArray' is a deprecated PRNGKeyArray after the jax version gets updated. Could you please try it again and see if this error gets resolved? I just ran it and looks like everything is runnable now.
![image](https://github.com/user-attachments/assets/181e67b5-612b-4391-b4e4-52f530481d86)

**Comment by 957-z** [comment]
Thank you for your efforts and could you give me the latest verison of Distance_AF_embedding_FullMSA.ipynb

**Comment by Zhang038** [comment]
There is no change in Distance_AF_embedding_FullMSA.ipynb, you can directly run it.

**Comment by 957-z** [comment]
I have tried it agian and it works now. Thank you very much!
